apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: kubeflow
spec:
  storageClassName: mysql
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
